name: 'Satellite file upload (alpha)'
description: 'Upload a new Kubernetes resource to IBM Cloud Satellite (alpha)'
inputs:
  apikey:
    description: 'IBM Cloud API key'
    required: true
  satelliteHost:
    description: 'IBM Cloud Satellite API endpoint'
    required: true
  tokenHost:
    description: 'IBM Cloud IAM endpoint'
    required: true
  channelUuid:
    description: 'Satellite Config channelUuid'
    required: true
  filename:
    description: 'File to upload'
    required: true
  versionName:
    description: 'Name of the new version'
    required: true
outputs:
  versionUuid:
    description: 'The ID of the new version uploaded'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: arrow-up-circle
  color: blue
